apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: "spark-send-rcvr.users"
  namespace: "lightbend"
  labels:
    strimzi.io/cluster: "pipelines-strimzi" 
spec:
  topicName: "spark-send-rcvr.users"
  partitions: 3
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
